// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseOutputDirectory() {
  return window['go']['main']['App']['ChooseOutputDirectory']();
}

export function DefaultOutputFileName() {
  return window['go']['main']['App']['DefaultOutputFileName']();
}

export function GetSelection(arg1, arg2) {
  return window['go']['main']['App']['GetSelection'](arg1, arg2);
}

export function RunCaptureSession(arg1) {
  return window['go']['main']['App']['RunCaptureSession'](arg1);
}

export function StopSession() {
  return window['go']['main']['App']['StopSession']();
}
