// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseOutputDirectory():Promise<string>;

export function DefaultOutputFileName():Promise<string>;

export function GetSelection(arg1:number,arg2:number):Promise<main.RegionSelection>;

export function RunCaptureSession(arg1:main.CaptureSessionParams):Promise<string>;

export function StopSession():Promise<void>;
