// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseOutputDirectory():Promise<string>;

export function DefaultOutputFileName():Promise<string>;

export function GetSelectedRegion():Promise<main.CaptureRegionInput>;

export function Greet(arg1:string):Promise<string>;

export function RunTestSession(arg1:main.TestSessionParams):Promise<void>;

export function StopSession():Promise<void>;
