// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseOutputDirectory() {
  return window['go']['main']['App']['ChooseOutputDirectory']();
}

export function DefaultOutputFileName() {
  return window['go']['main']['App']['DefaultOutputFileName']();
}

export function GetSelectedRegion() {
  return window['go']['main']['App']['GetSelectedRegion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunTestSession(arg1) {
  return window['go']['main']['App']['RunTestSession'](arg1);
}
